service: gpu-roi
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  memorySize: 256
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:GetItem
          - dynamodb:Query
          - dynamodb:BatchWriteItem
          - dynamodb:Scan
        Resource:
          - Fn::GetAtt:
            - PricesTable
            - Arn
          - Fn::GetAtt:
              - DevicesTable
              - Arn


functions:
  update-btc-price-lambda:
    handler: serverless/src/handlers/updateBtcPriceLambda.handler
    events:
      - schedule: rate(2 hours)
    environment:
      BTC_URL: "https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT"

  update-usd-price-lambda:
    handler: serverless/src/handlers/updateUsdPrice.handler
    events:
      - schedule: rate(1 day)
    environment:
      USD_URL: "https://api-dolar-argentina.herokuapp.com/api/dolarblue"

  update-devices-prices-lambda:
    handler: serverless/src/handlers/updateDevicesPricesLambda.handler
    events:
      - schedule: rate(1 day)
    environment:
      DEVICES_URL: "https://www.hardgamers.com.ar/search?text="

  import-devices-lambda:
    handler: serverless/src/handlers/importDevices.handler
    environment:
      DEVICES_URL: "https://api2.nicehash.com/main/api/v2/public/profcalc/devices"

  get-devices-lambda:
    handler: serverless/src/handlers/getDevicesLambda.handler
    events:
      - httpApi:
          path: /devices
          method: GET


resources:
  Resources:
    DevicesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Devices
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        AttributeDefinitions:
          - AttributeName: DeviceId
            AttributeType: S
          - AttributeName: Paying
            AttributeType: N
        KeySchema:
          - AttributeName: DeviceId
            KeyType: HASH
          - AttributeName: Paying
            KeyType: RANGE

    PricesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Prices
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
        AttributeDefinitions:
          - AttributeName: Type
            AttributeType: S
        KeySchema:
          - AttributeName: Type
            KeyType: HASH
