service: gpu-roi
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  memorySize: 128
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource:
          Fn::GetAtt:
            - PricesTable
            - Arn


functions:
  get-btc-price-lambda:
    handler: serverless/src/handlers/getBtcPrice.handler
    events:
      - schedule: rate(2 hours)
      - httpApi:
          path: /api/btc
          method: get
    environment:
      BTC_URL: "https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT"

  get-devices-lambda:
    handler: serverless/src/getDevices.handler
    events:
      - httpApi:
          path: /api/devices
          method: get

resources:
  Resources:
    DevicesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Devices
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        AttributeDefinitions:
          - AttributeName: DeviceId
            AttributeType: S
          - AttributeName: Paying
            AttributeType: N
        KeySchema:
          - AttributeName: DeviceId
            KeyType: HASH
          - AttributeName: Paying
            KeyType: RANGE

    PricesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Prices
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
        AttributeDefinitions:
          - AttributeName: Type
            AttributeType: S
        KeySchema:
          - AttributeName: Type
            KeyType: HASH
