app:
  endpoints:
    devices: https://api2.nicehash.com/main/api/v2/public/profcalc/devices
    usd: https://api-dolar-argentina.herokuapp.com/api/dolarblue

logging:
  level:
    ar.com.frupp: info
    org.hibernate.SQL: error
    org.hibernate.type.descriptor.sql.BasicBinder: error

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/GPU_ROI
    username: root
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
